### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by spurgeonbj** [cookiecutter-openedx/openedx-plugin-example#10]
Dear Lawrence, 

Thanks a ton for this wonderful endevour.

The link https://github.com/cookiecutter-openedx/openedx-plugin-example/blob/main/openedx_plugin/student/registration.py appears to be broken.

Can you kindly check this please?

God bless you abundantly in all that concerns you!

**Comment by lpm0073** [comment]
thanks for pointing that out. now fixed and merged in main :)
