### ISSUE TITLE
Unknown Command 

### ISSUE THREAD

**Issue by jkariscodes** [cookiecutter-openedx/openedx-plugin-example#14]
Hi. This is an awesome repository for extending Open edX base functionality. I am having an issue with the following instruction:

`tutor local run lms ./manage.py lms openedx_plugin_init`

which shows the following output

`Unknown command: 'openedx_plugin_init'`

As shown in the following screenshot

![image](https://github.com/cookiecutter-openedx/openedx-plugin-example/assets/23359514/e7c1eb47-00f5-4567-b0f5-06b0be19d2b3)

I am testing it in a local deployment using WSL following the documentation's instructions.

**Comment by lpm0073** [comment]
Hi @jkariscodes , what exactly was the cause of this error? was it related in any way to deploying Palm?

**Comment by jkariscodes** [comment]
@lpm0073 I realized it was caused by missing the requirements for the OpenedX plugin. Thank you for creating a guide on adding functionality to OpenedX using Django apps.
