### ISSUE TITLE
Facing issues while installation process

### ISSUE THREAD

**Issue by zameel7** [cookiecutter-openedx/openedx-plugin-example#18]
Steps done:
- Added plugin to the ```private.txt```
- Run ```tutor k8s launch```
- Create and migrate migrations for lms and cms
- Configuration data added -> openedx_plugin_init

Facing issue:
- While trying to add configuration data for openedx_plugin_api by running: ```tutor k8s exec lms ./manage.py lms openedx_plugin_api_init```, got this error

```
Traceback (most recent call last):
  File "./manage.py", line 106, in <module>
    execute_from_command_line([sys.argv[0]] + django_args)
  File "/openedx/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/openedx/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/openedx/venv/lib/python3.8/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/openedx/venv/lib/python3.8/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/openedx/venv/lib/python3.8/site-packages/openedx_plugin_api/management/commands/openedx_plugin_api_init.py", line 42, in handle
    raise Exception("Missing required parameters")
Exception: Missing required parameters
command terminated with exit code 1
```

The error seems to be raised because the handle function inside openedx_plugin_api_init tries to get PLUGIN_API_USER_EMAIL,  PLUGIN_API_USER_NAME,  PLUGIN_API_USER_PASSWORD, OPENEDX_COMPLETE_DOMAIN_NAME, which is being taken from os.env.

https://github.com/cookiecutter-openedx/openedx-plugin-example/blob/1d343d5bc107ce3c9ff73923e046a449ee45b755/openedx_plugin_api/management/commands/openedx_plugin_api_init.py#L20C1-L25C78

Should we be adding these to the env or somewhere in the plugin?

**Comment by zameel7** [comment]
@lpm0073 , I don't see these anywhere in the cookiecutter code base. Could you please confirm that it is to be there in the cookiecutter itself?

**Comment by zameel7** [comment]
Shouldn't that be in the .env inside the container?

**Comment by lpm0073** [comment]
Not by default. it depends on how you deployed the pod. i checked a couple of installations earlier today and none of the four variables were set in the lms pods.

**Comment by lpm0073** [comment]
checking in on this issue. did you resolve the problems you were having?

**Comment by zameel7** [comment]
Yep, I added those values and it worked!

**Comment by lpm0073** [comment]
Excellent! closing this issue :)
