### ISSUE TITLE
Quickstart Deprecated in favour of launch

### ISSUE THREAD

**Issue by graeme44** [cookiecutter-openedx/openedx-plugin-example#21]
[Quickstart has been Deprecated](https://github.com/overhangio/tutor/blob/3d3abeb8eff1a1f87c58f059825f432e59849d17/CHANGELOG.md#v1510-2022-12-13) in favour of `launch` (as of Tutor v15.1.0)

**Comment by graeme44** [comment]
Also getting an error when trying to set up plugins using tutor, version 17.0.3:

```
tutor local run lms ./manage.py lms openedx_plugin_api_init
docker compose -f '/Users/x/Library/Application Support/tutor/env/local/docker-compose.yml' -f '/Users/x/Library/Application Support/tutor/env/local/docker-compose.prod.yml' --project-name tutor_local run --rm lms ./manage.py lms openedx_plugin_api_init
[+] Creating 6/0
 ✔ Container tutor_local-smtp-1           Running                                                             0.0s
 ✔ Container tutor_local-mysql-1          Running                                                             0.0s
 ✔ Container tutor_local-permissions-1    Created                                                             0.0s
 ✔ Container tutor_local-redis-1          Running                                                             0.0s
 ✔ Container tutor_local-mongodb-1        Running                                                             0.0s
 ✔ Container tutor_local-elasticsearch-1  Running                                                             0.0s
[+] Running 1/1
 ✔ Container tutor_local-permissions-1  Started                                                               0.2s
Unknown command: 'openedx_plugin_api_init'
Type 'manage.py help' for usage.
Error: Command failed with status 1: docker compose -f /Users/x/Library/Application Support/tutor/env/local/docker-compose.yml -f /Users/x/Library/Application Support/tutor/env/local/docker-compose.prod.yml --project-name tutor_local run --rm lms ./manage.py lms openedx_plugin_api_init
```
Interestingly, I also had to create the `requirements` dir in `$(tutor config printroot)/env/build/openedx` – not sure if this is related to the new Tutor versions.

**Comment by lpm0073** [comment]
@graeme44 , the command 'openedx_plugin_api_init' is a manage.py command that's part of this repo, and is located [here](https://github.com/cookiecutter-openedx/openedx-plugin-example/blob/main/openedx_plugin_api/management/commands/openedx_plugin_api_init.py). The error that you're seeing means that this plugin is not part of the build that you're running.

one simple way of verifying what is/isn't included in your build is to use tutor to start a terminal session inside the lms pod, and then run `pip list` to generate a list of all pip-installed packages. you *should* see this repo listed.

**Comment by graeme44** [comment]
Thanks @lpm0073, I see you have updated the README to use launch. The second issue is that [private.txt has been deprecated](https://github.com/overhangio/tutor/blob/3d3abeb8eff1a1f87c58f059825f432e59849d17/CHANGELOG.md#v1700-2023-12-09) (as of v17.0.0):

> [Deprecation] Adding Python packages to edx-platform via private.txt is no longer supported. Instead, users should bind-mount their requirement directories with tutor mounts add .... 

So `pip list` doesn't show this package, as it is not being installed.

**Comment by graeme44** [comment]
Closing, opened a new issue #22
